# Generated by Django 4.2 on 2024-01-31 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="is_completed",
        ),
    ]
